application {
  name = locust
}

clustering {
  ip = "0.0.0.0"
  port = 2551
  supervisor {
    ip = "0.0.0.0"
    port = 2551
  }
  min-nr-of-members = 1
}

xinuk {
  classes = [
    "pl.edu.agh.locust.model.AgentContainer",
    "pl.edu.agh.locust.model.SPPAgent",
    "pl.edu.agh.locust.algorithm.ParticleAgentMetrics",
    "pl.edu.agh.xinuk.simulation.GuiCellParticles",
    "breeze.linalg.DenseVector",
  ]
}

particle-agent {
  config {
    worldType = grid
    worldWidth = 400
    worldHeight = 256
    iterationsNumber = 100000
    iterationFinishedLogFrequency = 100
    skipEmptyLogs = false

    signalSuppressionFactor = 0.5
    signalAttenuationFactor = 1
    signalDisabled = true

    workersX = 1
    workersY = 24
    isSupervisor = true
    shardingMod = 144

    guiType = microParticles
    guiParticleSize = 1

    guiCellSize = 4
    guiStartIteration = 0
    guiUpdateFrequency = 1

    timestepDuration = 1.0

    agentContainerSize = 0.3
    agentAmount = 100000
    initialAreaCenterX = 14.92
    initialAreaCenterY = 38.4
    initialAreaRadius = 14.92

    averageSpeed = 0.0025
    previousDirectionWeight = 0.6
    randomComponentWeight = 0.05
    repulsionRange = 0.035
    alignmentRange = 0.135
    attractionRange = 0.3
    repulsionWeight = 1.5
    alignmentWeight = 3.0
    attractionWeight = 0.001
    occlusionThreshold = 25

    hopProbability = 0.01
    crowdedHopProbability = 0.2
    hopDuration = 1.0
    hopSpeed = 0.1

    activityPeriod = 270.0
    minimalInactivityPeriod = 90.0
    resumeMarchProbabilityPerSec = 0.01

    localOrderNeighbours = 5
  }
}
