application {
  name = locust
}

clustering {
  ip = "0.0.0.0"
  port = 2551
  supervisor {
    ip = "0.0.0.0"
    port = 2551
  }
  min-nr-of-members = 1
}

xinuk {
  classes = [
    "pl.edu.agh.locust.model.AgentContainer",
    "pl.edu.agh.locust.model.SPPAgent",
    "pl.edu.agh.locust.algorithm.ParticleAgentMetrics",
    "pl.edu.agh.xinuk.simulation.GuiCellParticles",
    "breeze.linalg.DenseVector",
  ]
}

particle-agent {
  config {
    worldType = grid
    worldWidth = 64
    worldHeight = 48
    iterationsNumber = 100000
    iterationFinishedLogFrequency = 100
    skipEmptyLogs = false

    signalSuppressionFactor = 0.5
    signalAttenuationFactor = 1
    signalDisabled = false

    workersX = 4
    workersY = 3
    isSupervisor = true
    shardingMod = 144

    guiType = particles
    guiParticleSize = 10

    guiCellSize = 15
    guiStartIteration = 0
    guiUpdateFrequency = 1

    timestepLength = 0.1

    agentContainerSize = 0.3
    meanAgentDensity = 200.0

    averageSpeed = 0.25
    previousDirectionWeight = 0.6
    randomComponentWeight = 0.05
    repulsionRange = 0.035
    alignmentRange = 0.135
    attractionRange = 0.3
    repulsionWeight = 1.0
    alignmentWeight = 1.0
    attractionWeight = 0.05
    occlusionThreshold = 25
  }
}
