application {
  name = locust
}

clustering {
  ip = "0.0.0.0"
  port = 2551
  supervisor {
    ip = "0.0.0.0"
    port = 2551
  }
  min-nr-of-members = 1
}

xinuk {
  classes = [
    "pl.edu.agh.locust.model.AgentContainer",
    "pl.edu.agh.locust.model.SPPAgent",
    "pl.edu.agh.locust.algorithm.ParticleAgentMetrics",
    "pl.edu.agh.xinuk.simulation.GridInfoCellParticles",
    "breeze.linalg.DenseVector",
  ]
}

particle-agent {
  config {
    worldType = grid
    worldWidth = 1
    worldHeight = 1
    iterationsNumber = 10000
    iterationFinishedLogFrequency = 100
    skipEmptyLogs = false

    signalSuppressionFactor = 0.5
    signalAttenuationFactor = 1
    signalDisabled = false

    workersX = 1
    workersY = 1
    isSupervisor = true
    shardingMod = 144

    guiType = particles
    guiCellSize = 200
    guiStartIteration = 0
    guiUpdateFrequency = 1

    agentContainerSize = 100 
    meanAgentDensity = 0.05
  }
}
